import {
    AccountBalanceOutlined,
    ArticleOutlined,
    AutoStoriesOutlined,
    BeachAccessOutlined,
    BloodtypeOutlined,
    CakeOutlined,
    CalculateOutlined,
    CameraAltOutlined,
    CardGiftcardOutlined,
    CheckroomOutlined,
    ChildFriendlyOutlined,
    CleaningServicesOutlined,
    CookieOutlined,
    DirectionsBusFilledOutlined,
    DirectionsCarFilledOutlined,
    FastfoodOutlined,
    FlightOutlined,
    HomeOutlined,
    LockOutlined,
    MonetizationOnOutlined,
    PedalBikeOutlined,
    PetsOutlined,
    ShoppingBagOutlined,
    StarBorderOutlined,
    TrendingUpOutlined,
    VideocamOutlined,
    PhoneOutlined,
    ChurchOutlined,
    ShoppingCartOutlined,
    PaymentOutlined,
  } from "@mui/icons-material";

export const Icons: { [key: string]: JSX.Element } = {
  "Casa": <HomeOutlined fontSize="small" />,
  "Livro": <AutoStoriesOutlined fontSize="small" />,
  "Dinheiro": <MonetizationOnOutlined fontSize="small" />,
  "Presente": <CardGiftcardOutlined fontSize="small" />,
  "Comida": <FastfoodOutlined fontSize="small" />,
  "Carro": <DirectionsCarFilledOutlined fontSize="small" />,
  "Roupa": <CheckroomOutlined fontSize="small" />,
  "Documento": <ArticleOutlined fontSize="small" />,
  "Praia": <BeachAccessOutlined fontSize="small" />,
  "Saúde": <BloodtypeOutlined fontSize="small" />,
  "Investimento": <TrendingUpOutlined fontSize="small" />,
  "Estrela": <StarBorderOutlined fontSize="small" />,
  "Avião": <FlightOutlined fontSize="small" />,
  "Bebê": <ChildFriendlyOutlined fontSize="small" />,
  "Banco": <AccountBalanceOutlined fontSize="small" />,
  "Cadeado": <LockOutlined fontSize="small" />,
  "Bicicleta": <PedalBikeOutlined fontSize="small" />,
  "Pet": <PetsOutlined fontSize="small" />,
  "Vassoura": <CleaningServicesOutlined fontSize="small" />,
  "Ônibus": <DirectionsBusFilledOutlined fontSize="small" />,
  "Bolo": <CakeOutlined fontSize="small" />,
  "Calculadora": <CalculateOutlined fontSize="small" />,
  "Cinema": <VideocamOutlined fontSize="small" />,
  "Câmera": <CameraAltOutlined fontSize="small" />,
  "Doce": <CookieOutlined fontSize="small" />,
  "Compras": <ShoppingBagOutlined fontSize="small" />,
  "Telefone": <PhoneOutlined fontSize="small" />,
  "Igreja": <ChurchOutlined fontSize="small" />,
  "Carrinho": <ShoppingCartOutlined fontSize="small" />,
  "Cartão": <PaymentOutlined fontSize="small" />,
};